r=int(input("Nhap vao ban kinh cua duong tron: "))
cv=float(2*r*3.14)
dt=float(3.14*r*r)
print("Dien tich cua duong tron co ban kinh 15 la = ",dt)
print("Chu vi cua duong tron co ban kinh 15 la = ",cv)